data = {
    "Add View Camera\nCtrl Left Click: Add Motion Camera": "添加视角相机\nCtrl+左键点击: 添加运动摄像机",
    "Use Cursor to Adjust Camera Lens": "以游标为基准调准相机焦距",
    "Switch Camera": "切换相机",
    "Motion Camera": "动态相机",
    "Add Motion Camera": "添加动态相机",
    "Left Click->Camera Name to Add Source": "左键->相机名字以添加源",
    "Right Click->End Add Mode": "右键->结束添加模式",
    "ESC->Cancel": "ESC->取消",
    "Sync to Selected": "同步到选中项",
    "Draw Modal": "模态绘制",
    "Motion Curve": "运动曲线",
    "Sub Camera": "子级相机",
    "There is no camera as child of this object": "此对象子级中没有相机物体",
    "Bake Motion Camera": "烘焙运动相机",
    "Pin Selected Camera": "固定选中相机",
    "Max Width": "最大宽度",
    "Max Height": "最大高度",
    "Camera Thumbnails": "相机缩略图",
    "Camera Thumbnails\nLeft Click: Enable\nCtrl: Pin Selected Camera\nCtrl Shift Click: Send to Viewer": "相机缩略图\n左键点击: 启用\nCtrl: 固定选中相机\nCtrl Shift 左键：生成缩略图",
    "Camera Helper": "相机助手"
}
